-- =============================================================================
-- DATABASE INITIALIZATION SCRIPT
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE SCHEMA IF NOT EXISTS school;

-- =============================================================================
-- ENUM TYPES
-- =============================================================================
CREATE TYPE school.account_status AS ENUM ('ACTIVE', 'LOCKED', 'BANNED', 'ARCHIVED');
CREATE TYPE school.auth_provider_enum AS ENUM ('LOCAL', 'MICROSOFT');
CREATE TYPE school.student_status_enum AS ENUM ('ADMITTED', 'ENROLLED', 'LEAVE_OF_ABSENCE', 'DROPPED', 'GRADUATED');
CREATE TYPE school.education_level_enum AS ENUM ('UNDERGRADUATE', 'GRADUATE');
CREATE TYPE school.student_type_enum AS ENUM ('REGULAR', 'IRREGULAR');
CREATE TYPE school.employee_status_enum AS ENUM ('ACTIVE', 'ON_LEAVE', 'RESIGNED', 'TERMINATED');
CREATE TYPE school.employee_type_enum AS ENUM ('FULL_TIME', 'PART_TIME');
CREATE TYPE school.delivery_mode_enum AS ENUM ('FACE_TO_FACE', 'ONLINE', 'HYBRID');
CREATE TYPE school.subject_status_enum AS ENUM ('ENROLLED', 'DROPPED', 'CREDITED');
CREATE TYPE school.enrollment_status_enum AS ENUM ('DRAFT', 'ENROLLED', 'DROPPED', 'REJECTED');
CREATE TYPE school.day_name_enum AS ENUM ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY');
CREATE TYPE school.service_status_enum AS ENUM ('PROBATIONARY', 'PERMANENT', 'CONTRACTUAL', 'SUBSTITUTE', 'CONSULTANT');
CREATE TYPE school.room_type_enum AS ENUM ('CLASSROOM', 'LAB', 'AUDITORIUM', 'ONLINE', 'FIELD');

-- =============================================================================
-- ENTITY TABLE DEFINITIONS
-- =============================================================================

-- I. USER MANAGEMENT
--    1. Accounts
CREATE TABLE school.accounts
(
    account_id       UUID                      NOT NULL DEFAULT gen_random_uuid(),
    status           school.account_status     NOT NULL DEFAULT 'ACTIVE',
    email            VARCHAR(255)              NOT NULL UNIQUE,
    password_hash    VARCHAR(255)              NULL,
    auth_provider    school.auth_provider_enum NOT NULL DEFAULT 'LOCAL',
    auth_provider_id VARCHAR(255)              NULL,
    created_at       TIMESTAMPTZ               NOT NULL DEFAULT NOW(),
    failed_attempts  INT                       NOT NULL DEFAULT 0,
    lock_time        TIMESTAMPTZ               NULL,
    PRIMARY KEY (account_id)
);

--    2. User Profiles
CREATE TABLE school.user_profiles
(
    account_id  UUID        NOT NULL,
    first_name  VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50) NULL,
    last_name   VARCHAR(50) NOT NULL,
    PRIMARY KEY (account_id)
);

--    3. Roles
CREATE TABLE school.roles
(
    role_no   BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (role_no)
);

--    4. Account Roles
CREATE TABLE school.account_roles
(
    account_id UUID   NOT NULL,
    role_no    BIGINT NOT NULL,
    PRIMARY KEY (account_id, role_no)
);

--    5. Students
CREATE TABLE school.students
(
    account_id          UUID                        NOT NULL,
    student_no          BIGINT                      NOT NULL,
    student_status      school.student_status_enum  NOT NULL DEFAULT 'ADMITTED',
    education_level     school.education_level_enum NOT NULL DEFAULT 'UNDERGRADUATE',
    student_type        school.student_type_enum    NOT NULL DEFAULT 'REGULAR',
    year_level          BIGINT                      NOT NULL DEFAULT 1,
    student_admitted_at TIMESTAMPTZ                 NOT NULL DEFAULT NOW(),
    course_code         VARCHAR(10)                 NOT NULL,
    block_no            BIGINT                      NULL,
    PRIMARY KEY (account_id)
);

--    6. Employees
CREATE TABLE school.employees
(
    account_id      UUID                        NOT NULL,
    employee_id     VARCHAR(10)                 NOT NULL,
    employee_status school.employee_status_enum NOT NULL DEFAULT 'ACTIVE',
    employee_type   school.employee_type_enum   NOT NULL,
    hired_at        TIMESTAMPTZ                 NOT NULL DEFAULT NOW(),
    PRIMARY KEY (account_id)
);

-- II. ACADEMIC STRUCTURE
--    1. Colleges
CREATE TABLE school.colleges
(
    college_code VARCHAR(10)  NOT NULL,
    college_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (college_code)
);

--    2. Courses
CREATE TABLE school.courses
(
    course_code  VARCHAR(10)                 NOT NULL,
    course_name  VARCHAR(100)                NOT NULL,
    course_tier  school.education_level_enum NOT NULL,
    college_code VARCHAR(10)                 NOT NULL,
    PRIMARY KEY (course_code)
);

--    3. Blocks
CREATE TABLE school.blocks
(
    block_no     BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    course_code  VARCHAR(10) NOT NULL,
    year_level   BIGINT      NOT NULL,
    block_number BIGINT      NOT NULL,
    PRIMARY KEY (block_no)
);

--    4. Course Subjects
CREATE TABLE school.course_subjects
(
    course_code  VARCHAR(10) NOT NULL,
    subject_code VARCHAR(10) NOT NULL,
    PRIMARY KEY (course_code, subject_code)
);

-- III. ACADEMIC OFFERINGS
--    1. Subjects
CREATE TABLE school.subjects
(
    subject_code VARCHAR(10)  NOT NULL,
    subject_name VARCHAR(100) NOT NULL,
    lec_units    BIGINT       NOT NULL DEFAULT 0,
    lab_units    BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (subject_code)
);

--    2. Subject Prereqs
CREATE TABLE school.subject_prereqs
(
    subject_code        VARCHAR(10) NOT NULL,
    prereq_subject_code VARCHAR(10) NOT NULL,
    PRIMARY KEY (subject_code, prereq_subject_code)
);

--    3. Sections
CREATE TABLE school.sections
(
    section_no       BIGINT                    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    available_slots  BIGINT                    NOT NULL DEFAULT 40,
    version          BIGINT                    NOT NULL DEFAULT 0,
    delivery_mode    school.delivery_mode_enum NOT NULL,
    subject_code     VARCHAR(10)               NOT NULL,
    employee_id      VARCHAR(10)               NOT NULL,
    academic_term_no BIGINT                    NOT NULL,
    PRIMARY KEY (section_no)
);

--    4. Section Blocks
CREATE TABLE school.section_blocks
(
    section_no BIGINT NOT NULL,
    block_no   BIGINT NOT NULL,
    PRIMARY KEY (section_no, block_no)
);

-- IV. ENROLLMENT
--    1. Enrollments
CREATE TABLE school.enrollments
(
    enrollment_no     BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    enrolled_at       TIMESTAMPTZ                   NOT NULL,
    created_at        TIMESTAMPTZ                   NOT NULL,
    enrollment_status school.enrollment_status_enum NOT NULL,
    account_id        UUID                          NOT NULL,
    academic_term_no  BIGINT                        NOT NULL,
    remarks           VARCHAR(500)                  NULL,
    PRIMARY KEY (enrollment_no)
);

--    2. Enrolled Sections
CREATE TABLE school.enrollment_sections
(
    enrollment_no  BIGINT                     NOT NULL,
    section_no     BIGINT                     NOT NULL,
    subject_status school.subject_status_enum NOT NULL,
    PRIMARY KEY (enrollment_no, section_no)
);

-- V. TIME & LOCATION
--    1. Schedules
CREATE TABLE school.schedules
(
    schedule_no BIGINT               NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    day_name    school.day_name_enum NOT NULL,
    start_time  TIME                 NOT NULL,
    end_time    TIME                 NOT NULL,
    section_no  BIGINT               NOT NULL,
    room_no     BIGINT               NOT NULL,
    PRIMARY KEY (schedule_no)
);

--    2. Service Histories
CREATE TABLE school.service_histories
(
    serv_history_no    BIGINT                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_date         DATE                       NOT NULL,
    end_date           DATE                       NULL,
    serv_status_during school.service_status_enum NOT NULL,
    account_id         UUID                       NOT NULL,
    PRIMARY KEY (serv_history_no)
);

--    3. School Years
CREATE TABLE school.school_years
(
    sy_no         BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sy_name       VARCHAR(50) NOT NULL,
    sy_start_date DATE        NOT NULL,
    sy_end_date   DATE        NOT NULL,
    PRIMARY KEY (sy_no)
);

--    4. Term Types
CREATE TABLE school.term_types
(
    term_type_id VARCHAR(2)  NOT NULL,
    term_name    VARCHAR(50) NOT NULL,
    PRIMARY KEY (term_type_id)
);

--    5. Academic Terms
CREATE TABLE school.academic_terms
(
    academic_term_no      BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    term_name             VARCHAR(50) NOT NULL,
    term_start_date       DATE        NOT NULL,
    term_end_date         DATE        NOT NULL,
    enrollment_start_date DATE        NOT NULL,
    enrollment_end_date   DATE        NOT NULL,
    sy_no                 BIGINT      NOT NULL,
    term_type_id          VARCHAR(2)  NOT NULL,
    PRIMARY KEY (academic_term_no)
);

--    6. Buildings
CREATE TABLE school.buildings
(
    building_no   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    building_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (building_no)
);

--    7. Rooms
CREATE TABLE school.rooms
(
    room_no       BIGINT                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    room_name     VARCHAR(50)           NOT NULL,
    room_capacity BIGINT                NULL,
    room_type     school.room_type_enum NOT NULL,
    building_no   BIGINT                NULL,
    PRIMARY KEY (room_no)
);

-- VI. GRADING
--    1. Grade Components
CREATE TABLE school.grade_components
(
    gc_no      BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    gc_name    VARCHAR(100) NOT NULL,
    max_score  BIGINT       NOT NULL,
    percent    BIGINT       NOT NULL,
    section_no BIGINT       NOT NULL,
    parent_gc  BIGINT       NULL,
    PRIMARY KEY (gc_no)
);

--    2. Grades
CREATE TABLE school.grades
(
    gc_no         BIGINT NOT NULL,
    enrollment_no BIGINT NOT NULL,
    raw_score     BIGINT NOT NULL,
    PRIMARY KEY (gc_no, enrollment_no)
);

-- =============================================================================
-- CONSTRAINTS
-- =============================================================================

-- I. USER MANAGEMENT
ALTER TABLE school.accounts
    ADD CONSTRAINT email_unique_ck UNIQUE (email),
    ADD CONSTRAINT acc_email_fmt_ck CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    ADD CONSTRAINT email_lower_ck CHECK (email = LOWER(email));

ALTER TABLE school.user_profiles
    ADD CONSTRAINT fk_user_profiles_account FOREIGN KEY (account_id) REFERENCES school.accounts (account_id) ON DELETE CASCADE;

ALTER TABLE school.roles
    ADD CONSTRAINT uq_roles_role_name UNIQUE (role_name);

ALTER TABLE school.account_roles
    ADD CONSTRAINT fk_account_roles_account FOREIGN KEY (account_id) REFERENCES school.accounts (account_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_account_roles_role FOREIGN KEY (role_no) REFERENCES school.roles (role_no) ON DELETE CASCADE;

ALTER TABLE school.students
    ADD CONSTRAINT fk_students_account FOREIGN KEY (account_id) REFERENCES school.accounts (account_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_students_course FOREIGN KEY (course_code) REFERENCES school.courses (course_code),
    ADD CONSTRAINT fk_students_block FOREIGN KEY (block_no) REFERENCES school.blocks (block_no),
    ADD CONSTRAINT uq_students_student_no UNIQUE (student_no);

ALTER TABLE school.employees
    ADD CONSTRAINT fk_employees_account FOREIGN KEY (account_id) REFERENCES school.accounts (account_id) ON DELETE CASCADE,
    ADD CONSTRAINT uq_employees_employee_id UNIQUE (employee_id);

-- II. ACADEMIC STRUCTURE
ALTER TABLE school.courses
    ADD CONSTRAINT fk_courses_college FOREIGN KEY (college_code) REFERENCES school.colleges (college_code);

ALTER TABLE school.blocks
    ADD CONSTRAINT fk_blocks_course FOREIGN KEY (course_code) REFERENCES school.courses (course_code),
    ADD CONSTRAINT chk_blocks_positive CHECK (year_level >= 1 AND block_number >= 1);

ALTER TABLE school.course_subjects
    ADD CONSTRAINT fk_cs_course FOREIGN KEY (course_code) REFERENCES school.courses (course_code) ON DELETE CASCADE,
    ADD CONSTRAINT fk_cs_subject FOREIGN KEY (subject_code) REFERENCES school.subjects (subject_code) ON DELETE CASCADE;

-- III. ACADEMIC OFFERINGS
ALTER TABLE school.subjects
    ADD CONSTRAINT chk_subject_units_nonnegative CHECK (lec_units >= 0 AND lab_units >= 0);

ALTER TABLE school.subject_prereqs
    ADD CONSTRAINT fk_prereq_subject FOREIGN KEY (subject_code) REFERENCES school.subjects (subject_code) ON DELETE CASCADE,
    ADD CONSTRAINT fk_prereq_required FOREIGN KEY (prereq_subject_code) REFERENCES school.subjects (subject_code) ON DELETE CASCADE;

ALTER TABLE school.sections
    ADD CONSTRAINT fk_sections_subject FOREIGN KEY (subject_code) REFERENCES school.subjects (subject_code),
    ADD CONSTRAINT fk_sections_employee FOREIGN KEY (employee_id) REFERENCES school.employees (employee_id) ON UPDATE CASCADE,
    ADD CONSTRAINT fk_sections_term FOREIGN KEY (academic_term_no) REFERENCES school.academic_terms (academic_term_no),
    ADD CONSTRAINT chk_section_slots CHECK (available_slots > 0);

ALTER TABLE school.section_blocks
    ADD CONSTRAINT fk_sb_section FOREIGN KEY (section_no) REFERENCES school.sections (section_no) ON DELETE CASCADE,
    ADD CONSTRAINT fk_sb_block FOREIGN KEY (block_no) REFERENCES school.blocks (block_no) ON DELETE CASCADE;

-- IV. ENROLLMENT
ALTER TABLE school.enrollments
    ADD CONSTRAINT fk_enrollments_account FOREIGN KEY (account_id) REFERENCES school.accounts (account_id),
    ADD CONSTRAINT fk_enrollments_term FOREIGN KEY (academic_term_no) REFERENCES school.academic_terms (academic_term_no);

ALTER TABLE school.enrollment_sections
    ADD CONSTRAINT fk_es_enrollment FOREIGN KEY (enrollment_no) REFERENCES school.enrollments (enrollment_no) ON DELETE CASCADE,
    ADD CONSTRAINT fk_es_section FOREIGN KEY (section_no) REFERENCES school.sections (section_no);

-- V. TIME & LOCATION
ALTER TABLE school.schedules
    ADD CONSTRAINT fk_schedules_section FOREIGN KEY (section_no) REFERENCES school.sections (section_no) ON DELETE CASCADE,
    ADD CONSTRAINT fk_schedules_room FOREIGN KEY (room_no) REFERENCES school.rooms (room_no) ON DELETE SET NULL,
    ADD CONSTRAINT chk_schedule_time CHECK (start_time < end_time),
    ADD CONSTRAINT no_room_overlap EXCLUDE USING GIST (
        room_no WITH =,
        day_name WITH =,
        tsrange(('2000-01-01'::date + start_time), ('2000-01-01'::date + end_time)) WITH &&
        ) WHERE (room_no IS NOT NULL);

ALTER TABLE school.service_histories
    ADD CONSTRAINT fk_sh_account FOREIGN KEY (account_id) REFERENCES school.accounts (account_id) ON DELETE CASCADE;

ALTER TABLE school.academic_terms
    ADD CONSTRAINT fk_at_sy FOREIGN KEY (sy_no) REFERENCES school.school_years (sy_no),
    ADD CONSTRAINT fk_at_type FOREIGN KEY (term_type_id) REFERENCES school.term_types (term_type_id),
    ADD CONSTRAINT chk_term_dates CHECK (term_start_date < term_end_date AND
                                         enrollment_start_date <= enrollment_end_date);

ALTER TABLE school.rooms
    ADD CONSTRAINT chk_room_capacity CHECK (room_capacity IS NULL OR room_capacity > 0),
    ADD CONSTRAINT fk_rooms_building FOREIGN KEY (building_no) REFERENCES school.buildings (building_no) ON DELETE SET NULL;

-- VI. GRADING
ALTER TABLE school.grade_components
    ADD CONSTRAINT fk_gc_section FOREIGN KEY (section_no) REFERENCES school.sections (section_no) ON DELETE CASCADE,
    ADD CONSTRAINT fk_gc_parent FOREIGN KEY (parent_gc) REFERENCES school.grade_components (gc_no) ON DELETE SET NULL,
    ADD CONSTRAINT chk_gc_percent CHECK (percent BETWEEN 0 AND 100),
    ADD CONSTRAINT chk_gc_values CHECK (max_score > 0 AND percent > 0 AND percent <= 100);

ALTER TABLE school.grades
    ADD CONSTRAINT fk_grades_gc FOREIGN KEY (gc_no) REFERENCES school.grade_components (gc_no) ON DELETE CASCADE,
    ADD CONSTRAINT fk_grades_enrollment FOREIGN KEY (enrollment_no) REFERENCES school.enrollments (enrollment_no) ON DELETE CASCADE;

-- =============================================================================
-- VIEW DEFINITIONS
-- =============================================================================

-- Student Profile View
CREATE OR REPLACE VIEW school.vw_student_profile AS
SELECT s.account_id,
       s.student_no,
       CONCAT(
               up.last_name, ', ',
               up.first_name,
               CASE
                   WHEN up.middle_name IS NOT NULL AND up.middle_name <> ''
                       THEN CONCAT(' ', SUBSTRING(up.middle_name, 1, 1), '.')
                   ELSE ''
                   END
       ) AS student_name,
       a.email,
       s.student_status,
       s.student_type,
       s.year_level,
       s.education_level
FROM school.students s
         JOIN school.user_profiles up ON s.account_id = up.account_id
         JOIN school.accounts a ON s.account_id = a.account_id;

-- Employee Profile View
CREATE OR REPLACE VIEW school.vw_employee_profile AS
SELECT e.account_id,
       e.employee_id,
       CONCAT(
               up.last_name, ', ',
               up.first_name,
               CASE
                   WHEN up.middle_name IS NOT NULL AND up.middle_name <> ''
                       THEN CONCAT(' ', SUBSTRING(up.middle_name, 1, 1), '.')
                   ELSE ''
                   END
       ) AS employee_name,
       a.email,
       e.employee_status,
       e.employee_type
FROM school.employees e
         JOIN school.user_profiles up ON e.account_id = up.account_id
         JOIN school.accounts a ON e.account_id = a.account_id;

-- Enrollment Details View
CREATE OR REPLACE VIEW school.vw_enrollment_details AS
SELECT e.enrollment_no,
       e.account_id                           AS student_account_id,
       e.academic_term_no,
       es.section_no,
       sub.subject_code,
       sub.subject_name,
       (sub.lec_units + sub.lab_units)        AS total_units,
       sec.delivery_mode,
       sch.day_name,
       sch.start_time,
       sch.end_time,
       r.room_name,
       (SELECT string_agg(CONCAT(c.course_code, ' ', b.year_level, '-', b.block_number), ', ')
        FROM school.section_blocks sb
                 JOIN school.blocks b ON sb.block_no = b.block_no
                 JOIN school.courses c ON b.course_code = c.course_code
        WHERE sb.section_no = sec.section_no) AS section_name
FROM school.enrollments e
         JOIN school.enrollment_sections es ON e.enrollment_no = es.enrollment_no
         JOIN school.sections sec ON es.section_no = sec.section_no
         JOIN school.subjects sub ON sec.subject_code = sub.subject_code
         LEFT JOIN school.schedules sch ON sec.section_no = sch.section_no
         LEFT JOIN school.rooms r ON sch.room_no = r.room_no;

-- Student Grades View
CREATE OR REPLACE VIEW school.vw_student_grades AS
SELECT g.enrollment_no,
       e.account_id AS student_account_id,
       s.student_no,
       sub.subject_code,
       sub.subject_name,
       sec.section_no,
       gc.gc_name,
       gc.percent   AS weight_percent,
       gc.max_score,
       g.raw_score,
       CAST(
               (CAST(g.raw_score AS DECIMAL) / NULLIF(gc.max_score, 0)) * gc.percent
           AS DECIMAL(5, 2)
       )            AS weighted_score
FROM school.grades g
         JOIN school.grade_components gc ON g.gc_no = gc.gc_no
         JOIN school.enrollments e ON g.enrollment_no = e.enrollment_no
         JOIN school.students s ON e.account_id = s.account_id
         JOIN school.sections sec ON gc.section_no = sec.section_no
         JOIN school.subjects sub ON sec.subject_code = sub.subject_code;

-- Student Credited Subjects
CREATE OR REPLACE VIEW school.vw_student_credited_subjects AS
SELECT e.account_id AS student_account_id,
       s.subject_code,
       s.subject_name,
       s.lec_units,
       s.lab_units,
       es.subject_status
FROM school.enrollment_sections es
         JOIN school.enrollments e ON es.enrollment_no = e.enrollment_no
         JOIN school.sections sec ON es.section_no = sec.section_no
         JOIN school.subjects s ON sec.subject_code = s.subject_code
WHERE es.subject_status = 'CREDITED';

-- SECTION GRADE SHEET
CREATE OR REPLACE VIEW school.vw_section_grade_sheet AS
SELECT ROW_NUMBER() OVER (ORDER BY e.enrollment_no, g.gc_no) AS view_id,
       sec.section_no,
       e.enrollment_no,
       e.account_id                                          AS student_account_id,
       CONCAT(up.last_name, ', ', up.first_name)             AS student_name,
       g.gc_no                                               AS component_id,
       g.raw_score
FROM school.enrollments e
         JOIN school.enrollment_sections es ON e.enrollment_no = es.enrollment_no
         JOIN school.sections sec ON es.section_no = sec.section_no
         JOIN school.user_profiles up ON e.account_id = up.account_id
         LEFT JOIN school.grades g ON e.enrollment_no = g.enrollment_no
         LEFT JOIN school.grade_components gc ON g.gc_no = gc.gc_no AND gc.section_no = sec.section_no
WHERE e.enrollment_status = 'ENROLLED';

-- Pending Enrollment Details
CREATE OR REPLACE VIEW school.vw_pending_enrollment_details AS
SELECT e.enrollment_no,
       e.enrollment_status,
       e.account_id                              AS student_account_id,
       s.student_no,
       CONCAT(up.last_name, ', ', up.first_name) AS student_name,
       at.term_name,
       es.section_no,
       sub.subject_code,
       sub.subject_name,
       (sub.lec_units + sub.lab_units)           AS units,
       c.course_code,
       (SELECT string_agg(
                       CONCAT(sch.day_name, ' ', sch.start_time, '-', sch.end_time, ' (', r.room_name, ')'),
                       '; '
               )
        FROM school.schedules sch
                 JOIN school.rooms r ON sch.room_no = r.room_no
        WHERE sch.section_no = es.section_no)    AS full_schedule
FROM school.enrollments e
         JOIN school.user_profiles up ON e.account_id = up.account_id
         JOIN school.students s ON e.account_id = s.account_id
         JOIN school.courses c ON s.course_code = c.course_code
         JOIN school.academic_terms at ON e.academic_term_no = at.academic_term_no
         JOIN school.enrollment_sections es ON e.enrollment_no = es.enrollment_no
         JOIN school.sections sec ON es.section_no = sec.section_no
         JOIN school.subjects sub ON sec.subject_code = sub.subject_code
WHERE e.enrollment_status = 'DRAFT';

-- =============================================================================
-- DEFAULT INSERTS
-- =============================================================================
INSERT INTO school.roles (role_name)
VALUES ('STUDENT'),
       ('PROFESSOR'),
       ('ADMIN');
INSERT INTO school.buildings (building_name)
VALUES ('University Grounds'),
       ('Virtual Campus');
INSERT INTO school.rooms (room_name, room_capacity, room_type, building_no)
VALUES ('FIELD', NULL, 'FIELD', 1);
INSERT INTO school.rooms (room_name, room_capacity, room_type, building_no)
VALUES ('MS TEAMS', NULL, 'ONLINE', 2);

-- =============================================================================
-- TRIGGERS (DATA INTEGRITY)
-- =============================================================================

-- GRADE PERCENTAGE 100% LIMIT
CREATE OR REPLACE FUNCTION school.check_grade_percentage_limit()
    RETURNS TRIGGER AS
$$
DECLARE
    existing_sum INTEGER;
    new_total    INTEGER;
BEGIN
    IF NEW.parent_gc IS NULL THEN
        SELECT COALESCE(SUM(percent), 0)
        INTO existing_sum
        FROM school.grade_components
        WHERE section_no = NEW.section_no
          AND parent_gc IS NULL
          AND gc_no IS DISTINCT FROM NEW.gc_no;

        new_total := existing_sum + NEW.percent;

        IF new_total > 100 THEN
            RAISE EXCEPTION 'Grade Component Violation: Section % total would be % (Limit 100)', NEW.section_no, new_total;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_enforce_max_percent ON school.grade_components;
CREATE TRIGGER trg_enforce_max_percent
    BEFORE INSERT OR UPDATE
    ON school.grade_components
    FOR EACH ROW
EXECUTE FUNCTION school.check_grade_percentage_limit();

-- STUDENT SCHEDULE OVERLAP CHECK
CREATE OR REPLACE FUNCTION school.check_student_schedule_conflict()
    RETURNS TRIGGER AS
$$
DECLARE
    conflict_data RECORD;
BEGIN
    SELECT es.section_no, s_existing.day_name, s_existing.start_time, s_existing.end_time
    INTO conflict_data
    FROM school.enrollment_sections es
             JOIN school.schedules s_existing ON es.section_no = s_existing.section_no
             JOIN school.schedules s_new ON s_new.section_no = NEW.section_no
    WHERE es.enrollment_no = NEW.enrollment_no
      AND s_existing.day_name = s_new.day_name
      AND (s_new.start_time < s_existing.end_time AND s_new.end_time > s_existing.start_time)
    LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION 'Schedule Conflict: Cannot enroll in Section %. It overlaps with existing Section % on % (% to %)',
            NEW.section_no,
            conflict_data.section_no,
            conflict_data.day_name,
            conflict_data.start_time,
            conflict_data.end_time;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_student_schedule ON school.enrollment_sections;
CREATE TRIGGER trg_check_student_schedule
    BEFORE INSERT
    ON school.enrollment_sections
    FOR EACH ROW
EXECUTE FUNCTION school.check_student_schedule_conflict();

-- EMPLOYEE SCHEDULE OVERLAP CHECK
CREATE OR REPLACE FUNCTION school.check_employee_schedule_conflict()
    RETURNS TRIGGER AS
$$
DECLARE
    current_emp_id VARCHAR;
    conflict_data  RECORD;
BEGIN
    SELECT employee_id
    INTO current_emp_id
    FROM school.sections
    WHERE section_no = NEW.section_no;

    SELECT s.section_no, s.start_time, s.end_time
    INTO conflict_data
    FROM school.schedules s
             JOIN school.sections sec ON s.section_no = sec.section_no
    WHERE sec.employee_id = current_emp_id
      AND s.day_name = NEW.day_name
      AND s.schedule_no IS DISTINCT FROM NEW.schedule_no
      AND (NEW.start_time < s.end_time AND NEW.end_time > s.start_time)
    LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION 'Employee Conflict: % is busy at this time in section %.', current_emp_id, conflict_data.section_no;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_employee_cloning ON school.schedules;
CREATE TRIGGER trg_prevent_employee_cloning
    BEFORE INSERT OR UPDATE
    ON school.schedules
    FOR EACH ROW
EXECUTE FUNCTION school.check_employee_schedule_conflict();

-- GRADE SCORE LIMIT CHECK
CREATE OR REPLACE FUNCTION school.check_grade_score_limit()
    RETURNS TRIGGER AS
$$
DECLARE
    allowed_max BIGINT;
BEGIN
    SELECT max_score
    INTO allowed_max
    FROM school.grade_components
    WHERE gc_no = NEW.gc_no;

    IF NEW.raw_score < 0 THEN
        RAISE EXCEPTION 'Score Violation: Raw score % cannot be negative.', NEW.raw_score;
    END IF;

    IF NEW.raw_score > allowed_max THEN
        RAISE EXCEPTION 'Score Violation: Raw score % exceeds max score % for this component.', NEW.raw_score, allowed_max;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_grade_score ON school.grades;
CREATE TRIGGER trg_check_grade_score
    BEFORE INSERT OR UPDATE
    ON school.grades
    FOR EACH ROW
EXECUTE FUNCTION school.check_grade_score_limit();

-- GRADE COMPONENT PARENT SECTION CHECK
CREATE OR REPLACE FUNCTION school.check_gc_parent_match()
    RETURNS TRIGGER AS
$$
DECLARE
    parent_section BIGINT;
BEGIN
    IF NEW.parent_gc IS NOT NULL THEN
        SELECT section_no
        INTO parent_section
        FROM school.grade_components
        WHERE gc_no = NEW.parent_gc;

        IF parent_section != NEW.section_no THEN
            RAISE EXCEPTION 'Hierarchy Error: Child component must belong to the same section as the parent component.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_gc_parent ON school.grade_components;
CREATE TRIGGER trg_check_gc_parent
    BEFORE INSERT OR UPDATE
    ON school.grade_components
    FOR EACH ROW
EXECUTE FUNCTION school.check_gc_parent_match();

-- STUDENT NO GENERATION
CREATE SEQUENCE IF NOT EXISTS school.student_no_seq START 1;
CREATE OR REPLACE FUNCTION school.generate_student_no()
    RETURNS TRIGGER AS
$$
DECLARE
    v_year_prefix TEXT;
    v_seq_num     BIGINT;
    v_seq_str     TEXT;
BEGIN
    IF NEW.student_no IS NULL THEN
        v_year_prefix := TO_CHAR(NOW(), 'YYYY');
        v_seq_num := NEXTVAL('school.student_no_seq');
        v_seq_str := v_seq_num::TEXT;
        NEW.student_no := (v_year_prefix || LPAD(v_seq_str, GREATEST(5, LENGTH(v_seq_str)), '0'))::BIGINT;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_generate_student_no ON school.students;
CREATE TRIGGER trg_generate_student_no
    BEFORE INSERT
    ON school.students
    FOR EACH ROW
EXECUTE FUNCTION school.generate_student_no();

-- EMPLOYEE ID GENERATION
CREATE SEQUENCE IF NOT EXISTS school.employee_id_seq START 1;
CREATE OR REPLACE FUNCTION school.generate_employee_id()
    RETURNS TRIGGER AS
$$
DECLARE
    v_year_prefix TEXT;
    v_seq_num     BIGINT;
    v_seq_str     TEXT;
BEGIN
    IF NEW.employee_id IS NULL OR NEW.employee_id = '' THEN
        v_year_prefix := TO_CHAR(NOW(), 'YYYY');
        v_seq_num := NEXTVAL('school.employee_id_seq');
        v_seq_str := v_seq_num::TEXT;
        NEW.employee_id := ('E' || v_year_prefix || LPAD(v_seq_str, GREATEST(4, LENGTH(v_seq_str)), '0'));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_generate_employee_id ON school.employees;
CREATE TRIGGER trg_generate_employee_id
    BEFORE INSERT
    ON school.employees
    FOR EACH ROW
EXECUTE FUNCTION school.generate_employee_id();

-- =============================================================================
-- INITIALIZE ADMIN ACCOUNT
-- =============================================================================
WITH acc AS (
    INSERT INTO school.accounts (email, password_hash)
        VALUES ('admin@plm.edu.ph', '$2a$10$urO3DSWyBBPEYuh8GQzXPu4KFlksPbWsc.pnRWY6Z0vTA.jsMWTkO')
        RETURNING account_id),
     profile AS (
         INSERT INTO school.user_profiles (account_id, first_name, last_name)
             SELECT account_id, 'Admin', 'User'
             FROM acc
             RETURNING account_id)
INSERT
INTO school.account_roles (account_id, role_no)
SELECT account_id, 3 -- ADMIN
FROM profile;
